name: Build & Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-release-android:
    name: Build and Release Android APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.8

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Configure Android Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}" > android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Update Version in pubspec.yaml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version:.*/version: $VERSION/" pubspec.yaml

      - name: Build split APKs
        run: flutter build apk --release --split-per-abi
      - name: Build universal APK
        run: flutter build apk --release

      - name: Rename APKs
        run: |
          cd build/app/outputs/flutter-apk
          mv app-arm64-v8a-release.apk atba-${{ github.ref_name }}-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk atba-${{ github.ref_name }}-armeabi-v7a.apk
          mv app-x86_64-release.apk atba-${{ github.ref_name }}-x86_64.apk
          mv app-release.apk atba-${{ github.ref_name }}-universal.apk


      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/flutter-apk/atba-*.apk
          name: apks


      - name: Release APKs
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/atba-*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-and-release-ios:
    name: Build and Release iOS IPA (Experimental)
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.8

      - name: Get Dependencies
        run: flutter pub get

      - name: Update Version in pubspec.yaml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i '' "s/^version:.*/version: $VERSION/" pubspec.yaml

      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r atba-${{ github.ref_name }}.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          path: build/ios/iphoneos/atba-${{ github.ref_name }}.ipa
          name: ipa

      - name: Release IPA
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/iphoneos/atba-${{ github.ref_name }}.ipa
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
